services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      TZ: America/Toronto
      MYSQL_ROOT_PASSWORD: yannick
      MYSQL_DATABASE: examgu
    ports:
      - "3307:3306"
    networks:
      - examgu-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$MYSQL_ROOT_PASSWORD --silent"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 20s

  backend:
    image: 17yannick17/examgu-backend:latest
    restart: unless-stopped
    environment:
      TZ: America/Toronto
      JAVA_TOOL_OPTIONS: "-Duser.timezone=America/Toronto"
      SPRING_JPA_OPEN_IN_VIEW: "true"
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/examgu?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: yannick
    ports:
      - "8080:8080"
    networks:
      - examgu-network
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    image: 17yannick17/examgu-frontend:latest
    restart: unless-stopped
    environment:
      TZ: America/Toronto
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    networks:
      - examgu-network
    depends_on:
      backend:
        condition: service_started

networks:
  examgu-network:

volumes:
  mysql_data: